repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff linting check
        entry: ruff check
        language: system
        types: [python]
        always_run: true
      - id: pyright
        name: pyright linting check
        entry: pyright
        language: system
        types: [python]
        always_run: true