repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: ruff check
        language: system
        types: [python]
      - id: pyright
        name: pyright
        entry: pyright
        language: node
        types: [python]